# ===============================
# DATABASE CONFIGURATION (POSTGRES - RENDER)
# ===============================

spring.datasource.url=jdbc:postgresql://dpg-d728iv5m5p6s73cst05g-a:5432/auto_cgyf
spring.datasource.username=auto
spring.datasource.password=AP3q8jGUPFuAqZvHjv1ZyzqZllwoFfrP
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.initialization-fail-timeout=0

# ===============================
# JPA CONFIGURATION
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.check_nullability=true

# ===============================
# SERVER CONFIGURATION
# ===============================

server.port=${PORT:8080}
spring.mvc.throw-exception-if-no-handler-found=false

# ===============================
# STORAGE CONFIGURATION
# ===============================

storage.type=local
app.storage.local.base-dir=uploads
